version: 1.0.{build}

image:
  - macOS
  - Ubuntu1804

for:
  # macOS 
  -
    matrix:
      only:
        - image: macOS

    clone_folder: ~/SimCenter

    init:
       - export PATH="$HOME/Qt/5.15.2/clang_64/bin:$HOME/venv3.8.6/bin:$PATH"
       - python -m pip install --upgrade pip
       - pip install conan
       - conan user
       - conan remote add simcenter https://api.bintray.com/conan/nheri-simcenter/simcenter       


    install:
       - uname
       - git clone https://github.com/NHERI-SimCenter/SimCenterBackendApplications.git
       - git clone https://github.com/NHERI-SimCenter/SimCenterCommon.git
       - git clone https://github.com/NHERI-SimCenter/quoFEM.git 

    build_script:
       # build SimCenterBackendApplications
       - cd SimCenterBackendApplications
       - chmod 'u+x' makeEXE.sh
       - ./makeEXE.sh
       - cd ..       
       
       # build quoFEM
       - cd quoFEM
       - chmod 'u+x' makeEXE.sh
       - ./makeEXE.sh
       - cd ..

    test_script:
       - qmake --version
       - gcc --version
       - python --version

  # Ubuntu1804 
  -
    matrix:
      only:
        - image: Ubuntu1804

    clone_folder: ~/SimCenter

    init:
       - export PATH="$HOME/Qt/5.15.2/gcc_64/bin:$HOME/venv3.8.6/bin:$PATH"
       - sudo update-alternatives --set gcc /usr/bin/gcc-9
       - sudo apt-get -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev
       - python -m pip install --upgrade pip
       - pip install conan
       - conan user
       - conan remote add simcenter https://api.bintray.com/conan/nheri-simcenter/simcenter
       
    install:
       - uname
       - git clone https://github.com/NHERI-SimCenter/SimCenterBackendApplications.git       
       - git clone https://github.com/NHERI-SimCenter/SimCenterCommon.git
       - git clone https://github.com/NHERI-SimCenter/quoFEM.git              

    build_script:
       # build SimCenterBackendApplications
       - cd SimCenterBackendApplications
       - chmod 'u+x' makeEXE.sh
       - ./makeEXE.sh
       - cd ..
       
       # build quoFEM
       - cd quoFEM
       - chmod 'u+x' makeEXE.sh
       - ls
       - ./makeEXE.sh
       - cd ..

    test_script:
       - qmake --version
       - gcc --version
       - python --version
