version: 1.0.{build}

image:
  - Ubuntu1804
  - macOS

for:
  # Ubuntu (AppImage)
  -
    matrix:
      only:
        - image: Ubuntu1804

    clone_folder: ~/test

    init:
       - sh: export PATH="$HOME/Qt/5.15.2/gcc_64/bin:$HOME/venv3.8.6/bin:$PATH"
       - sh: python -m pip install --upgrade pip
       - sh: pip install conan
       - sh: conan user
       - sh: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan       

    install:
       - sh: git clone https://github.com/fmckenna/testActions.git

    build_script:
       - sh: cd testActions
       - sh: gcc main.cpp
       - sh: ./a.out
       - sh: mkdir build
       - sh: cd build
       - sh: cmake ..
       - sh: make
       - sh: ls
       - sh: ./hello       

    test_script:
       - sh: qmake --version