version: 1.0.{build}

image:
  - macOS
  - Ubuntu1804

for:
  # macOS 
  -
    matrix:
      only:
        - image: macOS

    clone_folder: ~/SimCenter

    init:
       - export PATH="$HOME/Qt/5.15.2/clang_64/bin:$HOME/venv3.8.6/bin:$PATH"

    install:
       - ps : uname

    build_script:
       - ps: gcc --version

    test_script:
       - qmake --version


  # Ubuntu1804 
  -
    matrix:
      only:
        - image: Ubuntu1804

    clone_folder: ~/SimCenter

    init:
       - export PATH="$HOME/Qt/5.15.2/gcc/bin:$HOME/venv3.8.6/bin:$PATH"

    install:
       - ps : uname

    build_script:
       - ps: gcc --version

    test_script:
       - qmake --version
