version: 1.0.{build}

image:
  - Ubuntu1804
  - macOS
  - Visual Studio 2019

for:
  # Ubuntu (AppImage)
  -
    matrix:
      only:
        - image: Ubuntu1804

    clone_folder: ~/test

    init:
       - sh: export PATH="$HOME/Qt/5.15.2/gcc_64/bin:$HOME/venv3.8.6/bin:$PATH"

    install:
       - sh: git clone https://github.com/fmckenna/testActions.git

    build_script:
       - sh: cd testActions
       - sh: gcc main.cpp

    test_script:
       - sh: ls
       - sh: ./a.out
       - sh: python --version
       - sh: ls $HOME/venv3.8.6
       - sh: ls $HOME/Qt/5.15 