
trigger:
- main

resources:
  repositories:
  - repository: Common
    type: github
    endpoint: NHERI-SimCenter
    name: NHERI-SimCenter/SimCenterCommon
    ref: master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: Common

- script: echo Hello, world!
  displayName: 'Run a one-line script'

# use python 3.8
- task: UsePythonVersion@0
  displayName: Switch to Python 3.8
  inputs:
    versionSpec: '3.8' 
    addToPath: true 
    architecture: 'x64'

- script: |
    python --version
    python -m pip install --upgrade pip
    pip install conan
    conan user
    conan remote add simcenter https://api.bintray.com/conan/nheri-simcenter/simcenter       
    pwd
  displayName: 'Install conan'

- script: |
    conan install qt/5.15.2 --build missing
    qmake --version
    ls
  displayName: 'Install Qt'