
trigger:
- main

resources:
  repositories:
  - repository: Common
    type: github
    endpoint: NHERI-SimCenter
    name: NHERI-SimCenter/SimCenterCommon
    ref: master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: Common

# use python 3.8
- task: UsePythonVersion@0
  displayName: Switch to Python 3.8
  inputs:
    versionSpec: '3.8' 
    addToPath: true 
    architecture: 'x64'

- script: |
    python --version
    python -m pip install --upgrade pip
    pip install conan
    conan user
    conan remote add simcenter https://api.bintray.com/conan/nheri-simcenter/simcenter
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan    
  displayName: 'Install conan'

# conan install ./testActions --build missing
- script: |
    sudo apt-get update
    sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-0 libgtk2.0-dev nasm -y
    conan install qt/5.11.3@bincrafters/stable -o qt:qt3d=True -o qt:qtcharts=True -o qt:qttools=True -g virtualrunenv --build missing
    qmake --version
    ls
    ls ~/.conan/data
  displayName: 'Install Qt'