
trigger:
- main

resources:
  repositories:
  - repository: Common
    type: github
    endpoint: NHERI-SimCenter
    name: NHERI-SimCenter/SimCenterCommon
    ref: master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: Common

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    ls
    pwd
  displayName: 'Run a multi-line script'
