name: test compiling main.c

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
	     git clone https://github.com/fmckenna/testActions.git
	     pwd
	     ls
	     which gcc
