name: test compiling main.c

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
	
	
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
	
      - name: Install conan and python dependencies
        run: |
             python -m pip install --upgrade pip
	     pip install conan
             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: checkout repo
        run: |
             git clone https://github.com/fmckenna/testActions.git

      - name: build with gcc & run
        run: |
             cd testActions
             gcc main.cpp
             ./a.out


      - name: build with Cmake & run
        run: |
             cd testActions
             mkdir build
             cd build
             cmake ..
             make
             ls
             ./hello